blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail,name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/list/', views.post_list2, name='post_list2'),
    path('post/Campany/', views.post_campany_list, name='post_campany_list'),
    path('post/Campany/<int:pk>/', views.post_campany_detail,name='post_campany_detail'),
    path('post/Campany/new/', views.post_campany_new, name='post_campany_new'),
    path('post/Campany/<int:pk>/edit', views.post_campany_edit, name='post_campany_edit'),
    path('post/Campany/<pk>/remove/', views.post_campany_remove, name='post_campany_remove'),
    path('post/master/', views.master_select, name='master_select'),
    path('post/Division/', views.post_division_list, name='post_division_list'),
    path('post/Division/<int:pk>/', views.post_division_detail,name='post_division_detail'),
    path('post/Division/new/', views.post_division_new, name='post_division_new'),
    path('post/Division/<int:pk>/edit', views.post_division_edit, name='post_division_edit'),
    path('post/Division/<pk>/remove/', views.post_division_remove, name='post_division_remove'),
    path('post/Process/', views.post_process_list, name='post_process_list'),
    path('post/Process/<int:pk>/', views.post_process_detail,name='post_process_detail'),
    path('post/Process/new/', views.post_process_new.as_view(), name='post_process_new'),
    path('post/Process/<int:pk>/edit', views.post_process_edit, name='post_process_edit'),
    path('post/Process/<pk>/remove/', views.post_process_remove, name='post_process_remove'),
    path('post/Subprocess/', views.post_subprocess_list, name='post_subprocess_list'),
    path('post/Subprocess/<int:pk>/', views.post_subprocess_detail,name='post_subprocess_detail'),
    path('post/Subprocess/new/', views.post_subprocess_new.as_view(), name='post_subprocess_new'),
    path('post/Subprocess/<int:pk>/edit', views.post_subprocess_edit, name='post_subprocess_edit'),
    path('post/Subprocess/<pk>/remove/', views.post_subprocess_remove, name='post_subprocess_remove'),
    path('post/Failuretype/', views.post_failuretype_list, name='post_failuretype_list'),
    path('post/Failuretype/<int:pk>/', views.post_failuretype_detail,name='post_failuretype_detail'),
    path('post/Failuretype/new/', views.post_failuretype_new, name='post_failuretype_new'),
    path('post/Failuretype/<int:pk>/edit', views.post_failuretype_edit, name='post_failuretype_edit'),
    path('post/Failuretype/<pk>/remove/', views.post_failuretype_remove, name='post_failuretype_remove'),
    path('post/ExpenseItems/', views.post_expenseItems_list, name='post_expenseItems_list'),
    path('post/ExpenseItems/<int:pk>/', views.post_expenseItems_detail,name='post_expenseItems_detail'),
    path('post/ExpenseItems/new/', views.post_expenseItems_new, name='post_expenseItems_new'),
    path('post/ExpenseItems/<int:pk>/edit', views.post_expenseItems_edit, name='post_expenseItems_edit'),
    path('post/ExpenseItems/<pk>/remove/', views.post_expenseItems_remove, name='post_expenseItems_remove'),
    path('post/Order/', views.post_order_list, name='post_order_list'),
    path('post/Order/<int:pk>/', views.post_order_detail,name='post_order_detail'),
    path('post/Order/new/', views.post_order_new.as_view(), name='post_order_new'),
    path('post/Order/<int:pk>/edit', views.post_order_edit, name='post_order_edit'),
    path('post/Order/<pk>/remove/', views.post_order_remove, name='post_order_remove'),
    path('post/Order/allremove/', views.post_order_allremove, name='post_order_allremove'),
#
    path('api/division/get/', views.ajax_get_division, name='ajax_get_division'),
    path('api/process/get/', views.ajax_get_process, name='ajax_get_process'),

    path('api/divisionCategory/get/', views.ajax_get_divisionCategory, name='ajax_get_divisionCategory'),
    path('api/processCategory/get/', views.ajax_get_processCategory, name='ajax_get_processCategory'),
    path('api/subprocessCategory/get/', views.ajax_get_subprocessCategory, name='ajax_get_subprocessCategory'),

    path('post/Ordersearch/', views.post_ordersearch_list, name='post_ordersearch_list'),
    path('post/Order/<int:pk>/clientapproval', views.post_clientApproval, name='post_clientApproval'),

#電力
    path('post/MeterReading/', views.MeterReadingSelect, name='MeterReadingSelect'),
    path('post/MeterReading/Manage/', views.MeterReadingManage, name='MeterReadingManage'),
    path('post/Whmeter/list/', views.post_Whmeter_list, name='post_Whmeter_list'),
    path('post/Whmeter/new/', views.post_Whmeter_new, name='post_Whmeter_new'),
    path('post/Whmeter/<int:pk>/', views.post_Whmeter_detail,name='post_Whmeter_detail'),
    path('post/Whmeter/<int:pk>/edit', views.post_Whmeter_edit, name='post_Whmeter_edit'),
    path('post/Whmeter/<pk>/remove/', views.post_Whmeter_remove, name='post_Whmeter_remove'),
    path('post/Whmeterplace/list/', views.post_Whmeterplace_list, name='post_Whmeterplace_list'),
    path('post/Whmeterplace/new/', views.post_Whmeterplace_new, name='post_Whmeterplace_new'),
    path('post/Whmeterplace/<int:pk>/', views.post_Whmeterplace_detail,name='post_Whmeterplace_detail'),
    path('post/Whmeterplace/<int:pk>/edit', views.post_Whmeterplace_edit, name='post_Whmeterplace_edit'),
    path('post/Whmeterplace/<pk>/remove/', views.post_Whmeterplace_remove, name='post_Whmeterplace_remove'),
    path('post/MeterReading/list/', views.post_meterReading_list, name='post_meterReading_list'),
    path('post/MeterReading/new/', views.post_meterReading_new, name='post_meterReading_new'),
    path('post/MeterReading/<int:pk>/', views.post_meterReading_detail,name='post_meterReading_detail'),
    path('post/MeterReading/<int:pk>/edit', views.post_meterReading_edit, name='post_meterReading_edit'),
    path('post/MeterReading/<pk>/remove/', views.post_meterReading_remove, name='post_meterReading_remove'),
    path('post/MeterReadingsearch/', views.post_meterReadingsearch_list, name='post_meterReadingsearch_list'),
    path('post/MeterReading/monthly/add/', views.post_meterReading_monthly, name='post_meterReading_monthly'),
    path('post/MeterReading/monthly/', views.MeterReading_monthly, name='MeterReading_monthly'),
    path('post/MeterReading/camera/', views.post_meterReading_camera, name='post_meterReading_camera'),
    path('post/MeterReading/export/', views.meterReading_export, name='meterReading_export'),
    path('post/MeterReading/csv/', views.post_meterReading_export, name='post_meterReading_export'),

#検針者用
    path('post/MeterReading/Rmonthly/', views.MeterReading_Rmonthly, name='MeterReading_Rmonthly'),
    path('post/MeterReading/Rlist/', views.post_meterReading_Rlist, name='post_meterReading_Rlist'),
    path('post/MeterReading/<int:pk>/Redit/', views.post_meterReading_Redit, name='post_meterReading_Redit'),
    path('post/QRreader/R/', views.post_qrreader_R, name='post_qrreader_R'),
    path('post/Whmeter/QRR/', views.post_Whmeter_qrR, name='post_Whmeter_qrR'),
    path('post/MeterReading/ReditR/', views.post_meterReading_ReditR, name='post_meterReading_ReditR'),
    path('post/MeterReadingReadersearch/', views.post_meterReadingReadersearch_list, name='post_meterReadingReadersearch_list'),
    path('post/MeterReading/camera2/', views.post_meterReading_camera2, name='post_meterReading_camera2'),
    path('post/MeterReading/Rcamera2/', views.post_meterReading_Rcamera2, name='post_meterReading_Rcamera2'),

    path('post/QRreader/', views.QR_reader, name='QR_reader'),
    path('post/Whmeter/QR', views.post_Whmeter_qr, name='post_Whmeter_qr'),
#    path('post/camera/test', views.camera_test, name='camera_test'),
#    path('post/camera/test2', views.post_camera_test2, name='post_camera_test2'),
    path('post/cameraOCR/test3', views.post_cameraOCR_test3, name='post_cameraOCR_test3'),

#    path('post/QRtest2/', views.post_qr_test2, name='post_qr_test2'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import datetime,timedelta


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Campany(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    telephon = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Division(models.Model):
    name = models.CharField(max_length=200)
    campany = models.ForeignKey(Campany,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Process(models.Model):
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=50)
    division = models.ForeignKey(Division,on_delete=models.CASCADE)
    campany = models.ForeignKey(Campany,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Subprocess(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=20)
    codeM = models.CharField(max_length=20)
    campany = models.ForeignKey(Campany,on_delete=models.CASCADE)
    division = models.ForeignKey(Division,on_delete=models.CASCADE)
    process = models.ForeignKey(Process,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Failuretype(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ExpenseItems(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Order(models.Model):
    subjectName = models.CharField(max_length=200,blank=True,null=True)
    type = models.CharField(max_length=100,blank=True,null=True)
    campany = models.ForeignKey(Campany,on_delete=models.CASCADE,default=1,)
    division = models.ForeignKey(Division,on_delete=models.CASCADE,default=1)
    process = models.ForeignKey(Process,on_delete=models.CASCADE,default=1)
    chargeName = models.CharField(max_length=100,blank=True,null=True)
    subProcess = models.ForeignKey(Subprocess,on_delete=models.CASCADE,default=1)
    orderNo = models.CharField(max_length=50,blank=True,null=True)
    subjectDetail = models.TextField(max_length=1000,blank=True,null=True)
    app_date = models.DateField(blank=True,null=True)
    requestSection_M = models.BooleanField(default=False)
    requestSection_E = models.BooleanField(default=False)
    requestSection_C = models.BooleanField(default=False)
    wishStart_date = models.DateField(blank=True, null=True)
    wishEnd_date = models.DateField(blank=True, null=True)
    failuretype = models.ForeignKey(Failuretype,on_delete=models.CASCADE,default=2,)
    expenseItems = models.ForeignKey(ExpenseItems,on_delete=models.CASCADE,default=1,)
    budget = models.IntegerField(blank=True,null=True)
#客先事前措置
    safePremeasure_removal = models.BooleanField(default=False)
    safePremeasure_valve = models.BooleanField(default=False)
    safePremeasure_switsh = models.BooleanField(default=False)
    safePremeasure_gas = models.BooleanField(default=False)
#連絡
    safeContact_start = models.BooleanField(default=False)
    safeContact_intermediate = models.BooleanField(default=False)
    safeContact_complete = models.BooleanField(default=False)
#立会
    safeWitness_always = models.BooleanField(default=False)
    safeWitness_start = models.BooleanField(default=False)
    safeWitness_disassembly = models.BooleanField(default=False)
    safeWitness_intermediate = models.BooleanField(default=False)
    safeWitness_receipt = models.BooleanField(default=False)
    safeWitness_complete = models.BooleanField(default=False)
    safeWitness_test = models.BooleanField(default=False)
#作業環境
    safeEnvironment_hazardous = models.BooleanField(default=False)
    safeEnvironment_heavy = models.BooleanField(default=False)
    safeEnvironment_pit = models.BooleanField(default=False)
    safeEnvironment_dust = models.BooleanField(default=False)
    safeEnvironment_height = models.BooleanField(default=False)
    safeEnvironment_updown = models.BooleanField(default=False)
#
    safeEnvironment_other = models.CharField(max_length=100,blank=True,null=True)
#危険物質
    safeHazardous_ASH3 = models.BooleanField(default=False)
    safeHazardous_SO2 = models.BooleanField(default=False)
    safeHazardous_SO3 = models.BooleanField(default=False)
    safeHazardous_CO2 = models.BooleanField(default=False)
    safeHazardous_CO = models.BooleanField(default=False)
    safeHazardous_H2S = models.BooleanField(default=False)
#
    safeHazardous_other = models.CharField(max_length=100,blank=True,null=True)
#保護具
    safeProtecter_helmet = models.BooleanField(default=False)
    safeProtecter_shoes = models.BooleanField(default=False)
    safeProtecter_fallPrevention = models.BooleanField(default=False)
    safeProtecter_acid = models.BooleanField(default=False)
    safeProtecter_earplug = models.BooleanField(default=False)
    safeProtecter_gloves = models.BooleanField(default=False)
#
    safeProtecter_other = models.CharField(max_length=100,blank=True,null=True)
#着工前措置
    safePretreatment_rope = models.BooleanField(default=False)
    safePretreatment_barricade = models.BooleanField(default=False)
    safePretreatment_light = models.BooleanField(default=False)
    safePretreatment_guard = models.BooleanField(default=False)
#
    safePretreatment_other = models.CharField(max_length=100,blank=True,null=True)
#環境側面
    safeAspect_waste = models.BooleanField(default=False)
    safeAspect_liquid = models.BooleanField(default=False)
    safeAspect_oil = models.BooleanField(default=False)
    safeAspect_remaining = models.BooleanField(default=False)
#
    safeNotices = models.CharField(max_length=200,blank=True,null=True)
    leagalConfimation = models.BooleanField(default=False)
    clientApproval = models.BooleanField(default=False)
    safeApproval = models.BooleanField(default=False)
    mescoReception = models.BooleanField(default=False)
#
    comfirmed = models.BooleanField(default=False)
    comfirmed_M = models.BooleanField(default=False)
    comfirmed_E = models.BooleanField(default=False)
    comfirmed_C = models.BooleanField(default=False)
#
    acceptance = models.BooleanField(default=False)

    def approval_client(self):
        self.clientApproval = True
        self.save()

#    def __str__(self):
#        return self.id


#電力入力
class Place(models.Model):
    name = models.CharField(max_length=30)
    code = models.CharField(max_length=20)

    def __str__(self):
        return self.name

#電力計
class Whmeter(models.Model):
    name = models.CharField(max_length=100)
    tag = models.CharField(max_length=50)
#    place = models.CharField(max_length=30)
    place =  models.ForeignKey(Place,on_delete=models.CASCADE)
    magnification = models.IntegerField(default=1)
    unit = models.CharField(max_length=20,default='kWh')
    maxvalue = models.IntegerField(default=0)
    digits = models.IntegerField(default=5)
    decimalPoint = models.IntegerField(default=0)

    def __str__(self):
        return self.tag

#積算検針
class MeterReading(models.Model):
    Whmeter = models.ForeignKey(Whmeter,on_delete=models.CASCADE)
    integrated_Wh = models.FloatField(default=0)
    readed_date = models.DateTimeField(default=datetime.strptime("1001/01/01 00:00:00","%Y/%m/%d %H:%M:%S"))
    reader = models.CharField(max_length=20,blank=True,null=True)
    type = models.CharField(max_length=20,default=1)
    count_year = models.IntegerField(default=2021)
    count_month = models.IntegerField(default=1)
    number = models.IntegerField(default=0)
#    image = models.ImageField(upload_to='')

blog/templates/blog/base_request.html
{% load static %}
<html lang='Ja'>
    <head>
        <title>工事依頼安全衛生指示システム</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            <p class="top-menu"> <a href="{% url 'master_select' %}">マスタ</a></p>
            <p class="top-menu"> <small>(<a href="{% url 'post_order_list' %}">伝票処理</a>)</small></p>
        {% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
            <h1><a href="/">工事依頼安全衛生指示 テスト</a></h1>
        </div>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
        {% block content %}
        {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/base_test.html
{% load static %}
<html lang='ja'>
    <head>
        <title>工事依頼安全衛生指示システム</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            <p class="top-menu"> <a href="{% url 'QR_reader' %}">QR</a></p>
            <p class="top-menu"> <a href="{% url 'master_select' %}">マスタ</a></p>
            <p class="top-menu"> <small>(<a href="{% url 'post_order_list' %}">伝票処理</a>)</small></p>
        {% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
            <h1><a href="/">工事依頼安全衛生指示 テスト</a></h1>
        </div>

  <div class="content container">
      <div class="row">
          <div class="col-md-8">
          {% block content %}
          {% endblock %}
          </div>
      </div>
  </div>


  <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

     {% block extrajs %}
     {% endblock %}
  </body>
</html>

blog/templates/blog/master_select.html
{% extends 'blog/base_request.html' %}

{% block content %}

  <h2>マスタ選択</h2>
  <h2><a href="{% url 'post_campany_list' %}">会社</a></h2>
  <h2><a href="{% url 'post_division_list' %}">部門</a></h2>
  <h2><a href="{% url 'post_process_list' %}">工程</a></h2>
  <h2><a href="{% url 'post_subprocess_list' %}">設備</a></h2>
  <h2><a href="{% url 'post_failuretype_list' %}">工事区分</a></h2>
  <h2><a href="{% url 'post_expenseItems_list' %}">費目</a></h2>
  
<!--
  <p class="top-menu"> <a href="{% url 'post_list2' %}">リスト表示</a></p>
  <table border="1">
            <tr>
                 <th>日付</th>
                 <th>タイトル</th>
                 <th>内　　容</th>
            </tr>
            {% for post in posts %}
                <div class="post" >
                    <tr>
                      <td>{{ post.published_date}}</td>
                      <td><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></td>
                      <td>{{ post.text}}</td>
                    </tr>
                </div>

            {% endfor %}
  </table>
-->
{% endblock %}

blog/templates/blog/post_campany_edit.html
{% extends 'blog/base_request.html' %}

{% block content %}
    <h2>新規会社入力</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_division_list.html
{% extends 'blog/base_request.html' %}

{% block content %}
    <h1>部門マスタ</h1>
    <h4><a href="{% url 'post_division_new' %}">新規追加</a></h4>
      <table border="1">
            <tr>
                 <th width='30'>ID</th>
                 <th width='100'>部　門　名</th>
                 <th width='150'>会　社</th>
            </tr>

            {% for post in posts %}

                    <tr>
                      <td align='center'>{{ post.id}}</td>
                      <td><a href="{% url 'post_division_detail' pk=post.pk %}">{{ post.name }}</a></td>
                      <td>{{ post.campany.name}}</td>
                    </tr>

<!--
                <div class="post">
                    <div class="date">
                        <p>published: {{ post.published_date }}</p>
                    </div>
                    <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                    <p>{{ post.text|linebreaksbr }}</p>
                </div>
-->
            {% endfor %}

      </table>
{% endblock %}

blog/templates/blog/post_expenseItems_edit.html
{% extends 'blog/base_request.html' %}

{% block content %}
    <h2>新規費目入力</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_expenseItems_list.html
{% extends 'blog/base_request.html' %}

{% block content %}
    <h1>費目マスタ</h1>
    <h4><a href="{% url 'post_expenseItems_new' %}">新規追加</a></h4>
      <table border="1">
            <tr align="center">
                 <th width="30">ID</th>
                 <th width="200">費目名</th>
            </tr>

            {% for post in posts %}

                    <tr align="center">
                      <td>{{ post.id}}</td>
                      <td><a href="{% url 'post_expenseItems_detail' pk=post.pk %}">{{ post.name }}</a></td>
                    </tr>

            {% endfor %}

      </table>
{% endblock %}

blog/templates/blog/post_order_edit.html
{% extends 'blog/base_request.html' %}

{% block content %}
    <h2>新規案件入力</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

{% block extrajs %}
    <script>
      const campanyCategoryElement = $('#id_campany_category');
      const divisionCategoryElement = $('#id_division_category');
      const processCategoryElement = $('#id_process_category');
      const subprocessElement = $('#id_subProcess');

//会社選択時の部門抽出の関数
      const changeDivision = (select) => {
        divisionCategoryElement.children().remove();
        $.ajax({

          url: '{% url 'ajax_get_divisionCategory' %}',
          type: 'GET',
          data: {
            'pk':campanyCategoryElement.val(),
          }
        }).done(response => {
          for (const division of response.divisionCategoryList) {
            const option = $('<option>');
            option.val(division['pk']);
            option.text(division['name']);
            divisionCategoryElement.append(option);
          }
          if (select !== undefined) {
            divisionCategoryElement.val(select);
          }

        });

      };

      campanyCategoryElement.on('change', () => {
        changeDivision();
        changeProcess();
        changeSubprocess();
        document.getElementById("id_campany").value = document.getElementById("id_campany_category").value;
      });

      if (campanyCategoryElement.val()) {
        const selectedCategory = divisionCategoryElement.val();
        changeDivision(selectedCategory);
      }

//部門選択時の工程抽出の関数
      const changeProcess = (select) => {
        processCategoryElement.children().remove();
        $.ajax({

          url: '{% url 'ajax_get_processCategory' %}',
          type: 'GET',
          data: {
            'pk':divisionCategoryElement.val(),
          }
        }).done(response => {
          for (const process of response.processCategoryList) {
            const option = $('<option>');
            option.val(process['pk']);
            option.text(process['name']);
            processCategoryElement.append(option);
          }
          if (select !== undefined) {
            processCategoryElement.val(select);
          }

        });

      };

      divisionCategoryElement.on('change', () => {
        changeProcess();
        changeSubprocess();
        document.getElementById("id_division").value = document.getElementById("id_division_category").value;
      });

      if (divisionCategoryElement.val()) {
        const selectedCategory = processCategoryElement.val();
        changeProcess(selectedCategory);
      }
//工程選択時の設備抽出の関数
   const changeSubprocess = (select) => {
     subprocessElement.children().remove();
     $.ajax({

       url: '{% url 'ajax_get_subprocessCategory' %}',
       type: 'GET',
       data: {
         'pk':processCategoryElement.val(),
       }
     }).done(response => {
       for (const subprocess of response.subprocessCategoryList) {
         const option = $('<option>');
         option.val(subprocess['pk']);
         option.text(subprocess['name']);
         subprocessElement.append(option);
       }
       if (select !== undefined) {
         subprocessElement.val(select);
       }

     });

   };

   processCategoryElement.on('change', () => {
     changeSubprocess();
     document.getElementById("id_process").value = document.getElementById("id_process_category").value;
   });

   if (processCategoryElement.val()) {
     const selectedCategory = subprocessElement.val();
     changeSubprocess(selectedCategory);
   }


    </script>
{% endblock %}